version: "3"

services:
  pact-broker:
    image: pactfoundation/pact-broker:latest-multi@sha256:5261a9ee7176d76d77d19d3781be67827b231bed353c2cc2aacafb5eb5a6ee70
    links:
      - postgres
    ports:
      - 8000:9292
    restart: always
    environment:
      # PACT_BROKER_BASIC_AUTH_USERNAME: pact_workshop # If you want to enable Basic Authentication
      # PACT_BROKER_BASIC_AUTH_PASSWORD: pact_workshop
      PACT_BROKER_DATABASE_USERNAME: postgres
      PACT_BROKER_DATABASE_PASSWORD: password
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: postgres
      PACT_BROKER_DATABASE_CONNECT_MAX_RETRIES: "10"
      PACT_BROKER_PUBLIC_HEARTBEAT: "true"
  postgres:
    image: postgres@sha256:3962158596daaef3682838cc8eb0e719ad1ce520f88e34596ce8d5de1b6330a1
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
